konjstats(als,neb,551).
konjstats(als,root,162).
konjstats(bevor,neb,153).
konjstats(bevor,root,35).
konjstats(bis,neb,102).
konjstats(bis,root,29).
konjstats(damit,neb,570).
konjstats(damit,root,265).
konjstats(da,neb,959).
konjstats(da,root,294).
konjstats(daß,objc,10169).
konjstats(dass,objc,2037).
konjstats(daß,root,1805).
konjstats(dass,root,375).
konjstats(daß,subjc,3913).
konjstats(dass,subjc,816).
konjstats(ehe,neb,49).
konjstats(ehe,root,10).
konjstats(falls,neb,63).
konjstats(falls,root,24).
konjstats(indem,neb,275).
konjstats(indem,root,129).
konjstats(inwieweit,neb,30).
konjstats(inwieweit,root,13).
konjstats(je,neb,15).
konjstats(je,root,30).
konjstats(nachdem,neb,141).
konjstats(nachdem,root,40).
konjstats(obgleich,neb,61).
konjstats(obgleich,root,15).
konjstats(ob,objc,634).
konjstats(ob,root,201).
konjstats(ob,subjc,259).
konjstats(obwohl,neb,322).
konjstats(obwohl,root,80).
konjstats(ohne,neb,7).
konjstats(ohne,root,6).
konjstats(seit,neb,8).
konjstats(sobald,neb,82).
konjstats(sobald,root,19).
konjstats(sofern,neb,59).
konjstats(sofern,root,31).
konjstats(solange,neb,111).
konjstats(solange,root,30).
konjstats(so,neb,10).
konjstats(soviel,neb,7).
konjstats(soweit,neb,56).
konjstats(soweit,root,17).
konjstats(während,neb,305).
konjstats(während,root,98).
konjstats(weil,neb,1106).
konjstats(weil,root,573).
konjstats(wenngleich,neb,44).
konjstats(wenngleich,root,13).
konjstats(wenn,neb,3901).
konjstats(wenn,root,1007).
konjstats(wie,neb,1334).
konjstats(wie,objc,894).
konjstats(wie,root,430).
konjstats(wie,subjc,655).
konjstats(zumal,neb,43).
konjstats(zumal,root,18).
